spring:
  application:
    name: cloud-udemy-cart
  config:
    import: "optional:configserver:"
  cloud:
    config:
      profile: default
      discovery:
        enabled: true
        service-id: cloud-udemy-config
      retry:
        initial-interval: 2000
        multiplier: 1.5
        max-interval: 60000
        max-attempts: 100
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}